---
include:
  - project: 'm-team/tools/ci-voodoo'
    ref: 'master'
    file: 'ci-include/generic-ci.yml'
  - project: 'm-team/tools/ci-voodoo'
    ref: 'master'
    file: 'ci-include/pipeline-jobs.yml'
  - project: 'm-team/tools/ci-voodoo'
    ref: 'master'
    file: 'ci-include/pipeline-jobs-publish-to-repo.yml'
  - project: 'm-team/tools/ci-voodoo'
    ref: 'master'
    file: 'ci-include/github-status-sync.yml'

default:
  tags:
    - linux

variables:
  UPSTREAM_PROJECT: dianagudu/motley_cue
  STAGING_BRANCH_NAME: "staging"
  DOCKER_IMAGE_NAMESPACE: "marcvs/build"
  DOCKER_IMAGE_NAME: "universal"
  # MTEAM_CI_ADDITIONAL_PACKAGES_APT: libsasl2-dev libldap2-dev python3-dev
  # MTEAM_CI_ADDITIONAL_PACKAGES_YUM: cyrus-sasl-devel openldap-devel python3-devel
  # MTEAM_CI_ADDITIONAL_PACKAGES_ZYPPER: cyrus-sasl-devel openldap2-devel python3-devel

build-ubuntu-bionic:
  extends:
    - .build-ubuntu-bionic
  script:
    - |
      cat debian/rules \
      | sed s/"dh_virtualenv --python python3"/"dh_virtualenv --python python3.8"/ \
      > debian/new-rules
      cat debian/new-rules > debian/rules
      make debsource
      dpkg-buildpackage -uc -us

##########################################################################
# Integration (These might to to a central job def)
trigger-integration-tests:
  variables:
    TRIGGER_TOKEN: ${TRIGGER_TOKEN_OIDC_SSH_MOTLEY_CUE}
    API_TOKEN: ${API_TOKEN_OIDC_SSH_MOTLEY_CUE}
    ### Parameters for trigger-pipeline
    # TRIGGER_TOKEN
    # API_TOKEN
    # TRIGGER_PROJECT_NAME (default: m-team/tools/integration/test-ssh-oidc)
    # BRANCH_TO_TRIGGER (default: devel)
    # RESOLVE_DEPENDENCIES_REPO
    # RESOLVE_DEPENDENCIES_FALLBACK_REPO
    # CHILD_SHOULD both default to false
    # CHILD_SHOULD_PUBLISH: 'true'
    CHILD_SHOULD_INTEGRATION_TEST: 'true'
  extends:
    - .trigger-pipeline
 
 
 
 
