---
include:
  - 'https://git.scc.kit.edu/m-team/ci-voodoo/raw/master/ci-include/generic-ci.yml'
  - 'https://git.scc.kit.edu/m-team/ci-voodoo/raw/master/ci-include/pipeline-jobs-on-push.yml'

variables:
  STAGING_BRANCH_NAME: 'staging'
  DOCKER_IMAGE_NAMESPACE: 'marcvs/build'
  DOCKER_IMAGE_NAME: 'motley-cue'

#build-centos-7:
#  stage: build
#  tags:
#    - linux
#  image: marcvs/build_motley-cue_centos-7:1
#  before_script:
#    - sed "s@^default_python@default_python=/usr/bin/python3\n#default_python@" -i /usr/lib/rpm/brp-python-bytecompile
#    - echo "typing-extensions" >> requirements.txt
#  artifacts:
#    paths:
#      - "results/*"
#    name: "motley-cue_centos-7_$CI_COMMIT_REF_NAME"
#
#build-centos8:
#  stage: build
#  tags:
#    - linux
#  image: marcvs/build_motley-cue_centos-8:1
#  artifacts:
#    paths:
#      - "results/*"
#    name: "motley-cue_centos-8_$CI_COMMIT_REF_NAME"
#
#build-centos-stream:
#  stage: build
#  tags:
#    - linux
#  image: marcvs/build_motley-cue_centos-stream:1
#  artifacts:
#    paths:
#      - "results/*"
#    name: "motley-cue_centos-8_$CI_COMMIT_REF_NAME"
#
#
#build-debian-bookworm:
#  stage: build
#  tags:
#    - linux
#  image: marcvs/build_motley-cue_debian-bookworm:1
#  script:
#    - ls -la
#    - make debsource
#    - dpkg-buildpackage -uc -us
#
#    - mkdir results
#    - ls -la ..
#    - mv ../*deb ../*tar.xz ../*.changes ../*.buildinfo ../*.orig.tar.gz ../*.dsc results
#  artifacts:
#    paths:
#      - "results/*"
#    name: "motley-cue_debian-bookworm_$CI_COMMIT_REF_NAME"
#
#build-debian-bullseye:
#  stage: build
#  tags:
#    - linux
#  image: marcvs/build_motley-cue_debian-bullseye:1
#  script:
#    - ls -la
#    - make debsource
#    - dpkg-buildpackage -uc -us
#
#    - mkdir results
#    - ls -la ..
#    - mv ../*deb ../*tar.xz ../*.changes ../*.buildinfo ../*.orig.tar.gz ../*.dsc results
#  artifacts:
#    paths:
#      - "results/*"
#    name: "motley-cue_debian-bullseye_$CI_COMMIT_REF_NAME"
#
#build-debian-buster:
#  stage: build
#  tags:
#    - linux
#  image: marcvs/build_motley-cue_debian-buster:1
#  script:
#    - ls -la
#    - make debsource
#    - dpkg-buildpackage -uc -us
#
#    - mkdir results
#    - ls -la ..
#    - mv ../*deb ../*tar.xz ../*.changes ../*.buildinfo ../*.orig.tar.gz ../*.dsc results
#  artifacts:
#    paths:
#      - "results/*"
#    name: "motley-cue_debian-bullseye_$CI_COMMIT_REF_NAME"
#
#
#build-opensuse_leap-15.3:
#  stage: build
#  tags:
#    - linux
#  image: marcvs/build_motley-cue_opensuse-leap-15.3:1
#  artifacts:
#    paths:
#      - "results/*"
#    name: "motley-cue_opensuse_leap-15.3_$CI_COMMIT_REF_NAME"
#
#build-opensuse_leap-15.4:
#  stage: build
#  tags:
#    - linux
#  image: marcvs/build_motley-cue_opensuse-leap-15.4:1
#  artifacts:
#    paths:
#      - "results/*"
#    name: "motley-cue_opensuse_leap-15.4_$CI_COMMIT_REF_NAME"
#
#build-opensuse-tumbleweed:
#  stage: build
#  tags:
#    - linux
#  image: marcvs/build_motley-cue_opensuse-tumbleweed:1
#  artifacts:
#    paths:
#      - "results/*"
#    name: "motley-cue_opensuse-tumbleweed_$CI_COMMIT_REF_NAME"
#
#
#build-rockylinux-8.5:
#  stage: build
#  tags:
#    - linux
#  image: marcvs/build_motley-cue_rockylinux-8.5:1
#  artifacts:
#    paths:
#      - "results/*"
#    name: "motley-cue_rockylinux-8.5_$CI_COMMIT_REF_NAME"
#
#
#build-ubuntu-focal:
#  stage: build
#  tags:
#    - linux
#  image: marcvs/build_motley-cue_ubuntu-focal:1
#  script:
#    - make focal-debsource
#    - dpkg-buildpackage -uc -us
#
#    - mkdir results
#    - mv ../*deb ../*tar.xz ../*.changes ../*.buildinfo ../*.orig.tar.gz ../*.dsc results
#  artifacts:
#    paths:
#      - "results/*"
#    name: "motley-cue_ubuntu-focal_$CI_COMMIT_REF_NAME"
#
#build-ubuntu-hirsute:
#  stage: build
#  tags:
#    - linux
#  image: marcvs/build_motley-cue_ubuntu-hirsute:1
#  script:
#    - make focal-debsource
#    - dpkg-buildpackage -uc -us
#
#    - mkdir results
#    - mv ../*deb ../*tar.xz ../*.changes ../*.buildinfo ../*.orig.tar.gz ../*.dsc results
#  artifacts:
#    paths:
#      - "results/*"
#    name: "motley-cue_ubuntu-hirsute_$CI_COMMIT_REF_NAME"
#
#build-ubuntu-impish:
#  stage: build
#  tags:
#    - linux
#  image: marcvs/build_motley-cue_ubuntu-impish:1
#  script:
#    - make focal-debsource
#    - dpkg-buildpackage -uc -us
#
#    - mkdir results
#    - ls -la ..
#    - mv ../*deb ../*tar.xz ../*.changes ../*.buildinfo ../*.orig.tar.gz ../*.dsc results
#  artifacts:
#    paths:
#      - "results/*"
#    name: "motley-cue_ubuntu-impish_$CI_COMMIT_REF_NAME"
#
#build-ubuntu-jammy:
#  stage: build
#  tags:
#    - linux
#  image: marcvs/build_motley-cue_ubuntu-jammy:1
#  script:
#    - make focal-debsource
#    - dpkg-buildpackage -uc -us
#
#    - mkdir results
#    - ls -la ..
#    - mv ../*deb ../*tar.xz ../*.changes ../*.buildinfo ../*.orig.tar.gz ../*.dsc results
#  artifacts:
#    paths:
#      - "results/*"
#    name: "motley-cue_ubuntu-jammy_$CI_COMMIT_REF_NAME"
 
