---
include:
  - 'https://git.scc.kit.edu/m-team/ci-voodoo/raw/master/ci-include/generic-ci.yml'
  - 'https://git.scc.kit.edu/m-team/ci-voodoo/raw/master/ci-include/pipeline-jobs.yml'

variables:
  STAGING_BRANCH_NAME: 'staging'
  DOCKER_IMAGE_NAMESPACE: 'marcvs/build'
  DOCKER_IMAGE_NAME: 'motley-cue'


build-opensuse-15.4:
  extends:
    - .build-opensuse-154

build-centos-7:
  extends:
    - .build-centos-7
  script:
    - |
      # Force RPM's python-bytecompile script to use python3
      sed "s@^default_python@default_python=python3\n#default_python@" -i /usr/lib/rpm/brp-python-bytecompile
      echo "typing-extensions" >> requirements.txt
    - make rpms

build-ubuntu-bionic:
  extends:
    - .build-ubuntu-bionic
  script:
    - |
      cat debian/rules \
      | sed s/"dh_virtualenv --python python3"/"dh_virtualenv --python python3.8"/ \
      > debian/new-rules
      cat debian/new-rules > debian/rules
      make debsource
      dpkg-buildpackage -uc -us

integration-tests:
  extends:
    - .integration-tests-ssh-oidc

