---
include:
  - "https://codebase.helmholtz.cloud/m-team/tools/ci-voodoo/raw/master/ci-include/generic-ci.yml"
  - "https://codebase.helmholtz.cloud/m-team/tools/ci-voodoo/raw/master/ci-include/pipeline-jobs.yml"
  - "https://codebase.helmholtz.cloud/m-team/tools/ci-voodoo/raw/master/ci-include/pipeline-jobs-publish-to-repo.yml"
  - "https://codebase.helmholtz.cloud/m-team/tools/ci-voodoo/raw/master/ci-include/github-status-sync.yml"

default:
  tags:
    - linux

variables:
  UPSTREAM_PROJECT: dianagudu/motley_cue
  STAGING_BRANCH_NAME: "staging"
  DOCKER_IMAGE_NAMESPACE: "marcvs/build"
  DOCKER_IMAGE_NAME: "motley-cue"
  #PREREL_BRANCH_NAME: 'ci/adapt-to-pam-ssh-oidc'
  #TARGET_REPO: 'devel'
  # The following varialbes can be overwritten only in specific targets
  # See generic-ci.yml -> .repo-definition for the full list
  # REPO_BASE => deprecated
  # REPO_USER
  # REPO_HOST
  # PUBLISH_BUILD_RESULTS_REPO: 'devel'
  # PUBLISH_TESTED_RESULTS_REPO: 'prerel'
  # PUBLISH_MASTER_RESULTS_REPO: 'for-prod'
  # PREREL_BRANCH_NAME: 'prerel'
  # See generic-ci.yml -> .build-definition for the full list
  # DOCKER_IMAGE_VERSION
  # DOCKER_IMAGE_VERSION_WINDOWS


##########################################################################
# Integration (These might to to a central job def)
trigger-integration-tests:
  variables:
    TRIGGER_TOKEN: ${TRIGGER_TOKEN_OIDC_SSH_MOTLEY_CUE}
    API_TOKEN: ${API_TOKEN_OIDC_SSH_MOTLEY_CUE}
    # api token needs "read_api" privileges of developer
  extends:
    - .trigger-integration-tests-ssh-oidc
