FROM debian:buster

RUN apt-get update && apt-get upgrade -y && apt-get install -y build-essential\
    dh-make quilt python3-virtualenv dh-virtualenv python3-venv devscripts git\
    python3 python3-dev python3-pip python3-setuptools


#RUN git clone https://github.com/dianagudu/motley_cue.git
#RUN cd motley_cue && make debsource && dpkg-buildpackage -uc -us && \
#    mkdir /dist && cp /motley-cue[-_]* /dist && \
#    dpkg-deb -I /dist/motley-cue_*.deb
