#!/bin/sh

MASTER_BRANCH=refs/remotes/origin/master
VERSION_FILE=motley_cue/VERSION

DISTANCE=$(git rev-list --count HEAD ^$MASTER_BRANCH)
VERSION=$(cat $VERSION_FILE)
PREREL_VERSION="${VERSION}-pr${DISTANCE}"
echo "$PREREL_VERSION" > $VERSION_FILE

