###############################################
#DEBHELPER#
###############################################

dh_venv_safe_lib_symlinks_update() {
    SAVED_DIR=`pwd`
        cd $dh_venv_install_dir/lib
        PKG_PYTHONDIR=""
        PYTHON3_MAJOR=`python3 --version| cut -d\  -f 2 | cut -d\. -f 1`
        PYTHON3_MINOR=`python3 --version| cut -d\  -f 2 | cut -d\. -f 2`
        for PYTHONDIR in python*; do
            test -e $PYTHONDIR && {
                test -L $PYTHONDIR || {
                    # If it exists but is not a symlink, then we found the
                    # Python dir for the version this package was created for
                    PKG_PYTHONDIR=$PYTHONDIR
                    #echo "PKG_PYTHONDIR: $PKG_PYTHONDIR"
                } || true
            } || true
        done
        test -z $PKG_PYTHONDIR && {
            echo "Can not find python package dir"
            exit 44
        }
        if [ "x${PKG_PYTHONDIR}" = "xpython${PYTHON3_MAJOR}.${PYTHON3_MINOR}" ] ; then
            echo -n ""
        else
            echo "Package was packed for $PKG_PYTHONDIR adjusting symlinks for installed python${PYTHON3_MAJOR}.${PYTHON3_MINOR}"
            test -e python${PYTHON3_MAJOR}.${PYTHON3_MINOR} || {
                ln -s $PKG_PYTHONDIR python${PYTHON3_MAJOR}.${PYTHON3_MINOR}
            }
        fi
    cd $SAVED_DIR
}

dh_venv_install_compatible_python_if_required() {
    # install python 3.12.9, only if too new python3 is on the system,
    # since we're unable to support python3.13
    PY_MAJOR=$(echo "import sys; print(sys.version_info.major);" | python3)
    PY_MINOR=$(echo "import sys; print(sys.version_info.minor);" | python3)
    if [ "$PY_MAJOR" != "3" ]; then
        echo "Error python major version is not 3"
        exit 2
    fi
    if [ $PY_MINOR -ge 13 ]; then 
        # setup and install with pyenv
        VARTMP_MC=/var/tmp/motley_cue
        USRLIB_MC=/usr/lib/motley-cue
        if not [ -d $VARTMP_MC ]; then
            mkdir -p $VARTMP_MC
        fi
        export PYENV_ROOT=${VARTMP_MC}/pyenv
        pyenv install -s 3.12.9
        echo "Pyenv is done: $? \n"

        # echo -e "\n${USRLIB_MC}/bin:"
        # tree ${USRLIB_MC/bin}
        #
        # echo -e "\n${VARTMP_MC}:"
        # tree ${VARTMP_MC}

        # install that python interpreter in our venv
        if [ -d ${USRLIB_MC}/bin ]; then
            cd ${USRLIB_MC}/bin
            rm -f python
            ln -s ${VARTMP_MC}/pyenv/versions/3.12.9/bin/python python

            # Ensure proper PATH for the systemd service
            echo "PATH=${USRLIB_MC}/bin:${PATH}" >> /tmp/motley_cue.env
            cat /etc/motley_cue/motley_cue.env >> /tmp/motley_cue.env
            cat /tmp/motley_cue.env >> /etc/motley_cue/motley_cue.env
            rm /tmp/motley_cue.env
        fi
    fi 
}

case "$1" in
    configure|triggered|reconfigure)
        dh_venv_safe_lib_symlinks_update
        dh_venv_install_compatible_python_if_required
        systemctl enable motley-cue || update-rc.d motley-cue defaults || true
        systemctl restart motley-cue || service motley-cue restart || /etc/init.d/motley-cue restart || true
        systemctl restart nginx || service nginx restart || nginx -s reload || nginx || true
        ;;
esac
