###############################################
#DEBHELPER#
###############################################

case "$1" in
    remove|deconfigure)
        #$DH_VENV_DEBUG echo "$0 $1 called with $# args:" "$@"
        systemctl stop motley-cue || service motley-cue stop || /etc/init.d/motley-cue stop || true
        systemctl disable motley-cue || update-rc.d -f motley-cue remove || true
        rm -rf /usr/lib/motley-cue/bin >/dev/null 2>&1 || true
        rm -rf /usr/lib/motley-cue/lib >/dev/null 2>&1 || true
        ;;

    upgrade|failed-upgrade)
        systemctl restart motley-cue || service motley-cue restart || /etc/init.d/motley-cue restart || true
        ;;

    *)
        #echo >&2 "ERROR:" $(basename "$0") "called with unknown argument '$1'"
        #exit 1
        ;;
esac

systemctl restart nginx || service nginx restart || nginx -s reload || nginx || true